global:
  scrape_interval: "10s"
  evaluation_interval: "10s"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: mpromt
    metrics_path: /metrics
    static_configs:
      - targets:
          - "mpromt:2112"